#presumes the existence of a repository resource named 'target' with a project.json in the root directory
#presumes the existence of a repository resource named 'impower' with relevant scripts
parameters:
  - name: service_connection
    type: string
  - name: icon_url
    type: string
  - name: output_type
    type: string
    default: 'None'
  - name: package_version
    type: string
  - name: add_release_notes
    type: boolean
    default: false
  - name: trace_level
    type: string
    default: 'Warning'
  - name: is_alpha
    type: boolean
    default: false
  - name: target_resource_name
    type: string
    default: 'target'
  - name: use_hosted_agent
    type: boolean
    default: true
  - name: cli_version
    type: string
    default: WINDOWS_LEGACY
    values:
    - WINDOWS_MODERN
    - WINDOWS_LEGACY
    - CROSS_PLATFORM

stages:
- stage: Build
  displayName: 'Build'
  ${{ if parameters.use_hosted_agent }}:
    pool:
      vmImage: 'windows-latest'
  jobs:
  - job: BuildJob
    ${{ if parameters.use_hosted_agent }}:
      workspace:
        clean: all
    displayName: 'Build Package'
    steps:
    - checkout: ${{ parameters.target_resource_name }}
      displayName: 'Checkout Target Repository'
      path: target
      ${{ if parameters.add_release_notes }}:
        fetchDepth: 10
    - checkout: impower
      displayName: 'Checkout Impower Resources'
      path: impower
    - task: UiPathInstallPlatform@5
      name: install_platform
      ${{ if eq(parameters.cli_version,'WINDOWS_MODERN') }}:
        displayName: 'Install Platform (Windows Modern)'
        inputs:
          cliVersion: 'WIN_22.10.8438.32859'
      ${{ elseif eq(parameters.cli_version,'CROSS_PLATFORM') }}:
        displayName: 'Install Platform (Cross Platform)'
        inputs:
          cliVersion: 'X_22.10.8438.32859'
      ${{ else }}:
        displayName: 'Install Platform (Windows Legacy)'
    - ${{ if parameters.icon_url }}:
      - task: powershell@2
        name: add_icon_url
        displayName: 'Add Icon URL'
        inputs:
          targetType: 'filePath'
          filePath: '$(Agent.BuildDirectory)/impower/utilities/add_package_icon.ps1'
          workingDirectory: '$(Agent.BuildDirectory)/target/'
          arguments: >
            -path_to_project_json project.json
            -image_url ${{ parameters.icon_url }}
    - ${{ if parameters.add_release_notes }}:
      - task: powershell@2
        name: add_release_notes
        displayName: 'Add Release Notes'
        inputs:
          targetType: 'filePath'
          filePath: '$(Agent.BuildDirectory)/impower/utilities/add_release_notes.ps1'
          arguments: >
            -path_to_project_folder '$(Agent.BuildDirectory)/target'
    - task: UiPathPack@5
      name: pack_package
      displayName: 'Pack Package'
      inputs:
        ${{ if eq(parameters.package_version,'auto') }}:
          versionType: 'AutoVersion'
        ${{ elseif eq(parameters.package_version, 'build') }}:
          versionType: 'ManualVersion'
          version: '$(Build.BuildNumber)'
        ${{ else }}:
          versionType: 'CurrentVersion'
        projectJsonPath: $(Agent.BuildDirectory)/target/project.json
        outputPath: $(Build.ArtifactStagingDirectory)
        outputType: ${{ parameters.output_type }}
        orchestratorConnection: ${{ parameters.service_connection }}
        traceLevel: ${{ parameters.trace_level }}
    - ${{ if parameters.is_alpha }}:
      - task: powershell@2
        name: make_alpha
        displayName: 'Make Alpha/Prerelease'
        inputs:
          targetType: 'filePath'
          filePath: '$(Agent.BuildDirectory)/impower/utilities/nupkg_append_version_suffix.ps1'
          arguments: >
            -directory_path '$(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifact: 'UiPathPackage'
        publishLocation: 'pipeline'




